# Generated by Django 5.2.9 on 2025-12-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('ingredients', models.TextField(help_text='One per line')),
                ('steps', models.TextField(help_text='Step by line or paragraphs')),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
