# Generated by Django 6.0 on 2025-12-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('recipes', '0001_initial'), ('recipes', '0002_recipe_author_recipe_tags'), ('recipes', '0003_recipe_cook_time_minutes_alter_recipe_ingredients_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prep_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('ingredients', models.TextField(help_text='Comma-separated ingredients (e.g., 2 cups flour, 1/2 tsp salt, 3 eggs)')),
                ('steps', models.TextField(help_text='Number each step or separate paragraphs for each instruction')),
                ('author', models.CharField(blank=True, help_text='Recipe author', max_length=200)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('cook_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
